'use strict';

// Turning this app's settings into something the pubky-swap binaries will accept.
//
// Two rules run through everything here:
//
//   Nothing configurable goes on argv. Upstream resolves $PUBKY_SWAP_CONFIG ahead of the
//   environment and the flags, so a generated TOML is both the most direct way to configure the
//   daemon and the only way to guarantee that `--doctor` and `--show-config` report on exactly the
//   configuration the daemon will run with.
//
//   The child environment is built from a whitelist, never inherited wholesale. Any stray
//   PUBKY_SWAP_* variable in the container would be merged by figment at a layer *above* our file
//   and silently outrank it, so a typo in docker-compose.yml could quietly change a fee.

const path = require('path');
const paths = require('./paths');
const secrets = require('./secrets');
const toml = require('./toml');
const { writeAtomic } = require('./atomic');

const NETWORK = process.env.NETWORK || 'bitcoin';
const LND_IP = process.env.LND_IP || '';
const LND_GRPC_PORT = process.env.LND_GRPC_PORT || '10009';
const LND_DIR = process.env.LND_DIR || '/lnd';
const ELECTRS_IP = process.env.ELECTRS_IP || '';
const ELECTRS_PORT = process.env.ELECTRS_PORT || '50001';

// LND keeps its chain data under data/chain/bitcoin/<mainnet|testnet|signet|regtest>/.
const LND_NETWORK_DIR =
  { bitcoin: 'mainnet', testnet: 'testnet', signet: 'signet', regtest: 'regtest' }[NETWORK] || 'mainnet';

const HEADER =
  'Generated by the Pubky Swap Umbrel app. Edits here are overwritten every time the daemon\n' +
  'starts; change the settings in the web panel instead.\n' +
  'Secrets are deliberately absent: they are passed as PUBKY_SWAP_*__FILE paths.';

/** The backend settings both binaries share. */
function backends() {
  return {
    network: NETWORK,
    lightning_backend: 'lnd',
    lnd_address: `https://${LND_IP}:${LND_GRPC_PORT}`,
    lnd_cert_path: path.join(LND_DIR, 'tls.cert'),
    lnd_macaroon_path: path.join(LND_DIR, 'data', 'chain', 'bitcoin', LND_NETWORK_DIR, 'admin.macaroon'),
    electrum_url: `tcp://${ELECTRS_IP}:${ELECTRS_PORT}`,
    // Fund and claim from LND's own on-chain wallet, so there is no second seed to back up.
    wallet_backend: 'lnd',
  };
}

/**
 * The provider's configuration.
 *
 * Deliberately absent: `min_claim_window_blocks`, `rendezvous_iroh`, `peer_idle_ttl_secs` and
 * `electrum_timeout_secs`. Those are safety and behaviour constants the engine tunes for itself,
 * and pinning them here would mean an upstream safety improvement never reaches anyone.
 */
function providerConfig(cfg, statusAddr) {
  return {
    ...backends(),
    directions: cfg.directions.split(','),
    min_amount_sat: cfg.minAmount,
    max_amount_sat: cfg.maxAmount,
    base_fee_sat: cfg.baseFee,
    fee_ppm: cfg.feePpm,
    required_confirmations: cfg.confirmations,
    htlc_timeout_blocks: cfg.timeoutBlocks,
    onchain_fee_rate_sat_vb: cfg.onchainFeeRate,
    invoice_expiry_secs: cfg.invoiceExpiry,
    max_routing_fee_msat: cfg.maxRoutingFeeMsat,
    quote_ttl_secs: cfg.quoteTtl,
    broadcast_offer: cfg.broadcastOffer,
    allow_unsafe: cfg.allowUnsafe,

    max_concurrent_swaps: cfg.maxConcurrentSwaps,
    max_concurrent_per_peer: cfg.maxConcurrentPerPeer,
    max_total_exposure_sat: cfg.maxTotalExposureSat,
    max_exposure_per_peer_sat: cfg.maxExposurePerPeerSat,
    min_onchain_reserve_sat: cfg.minOnchainReserveSat,
    max_new_swaps_per_peer_per_hour: cfg.maxNewSwapsPerPeerPerHour,

    data_dir: paths.providerDir,
    status_addr: statusAddr,
    recovery_file: secrets.recoveryFilePath() || undefined,
  };
}

/**
 * The taker's configuration for one run.
 *
 * `data_dir` is the whole point of this function. An earlier build never passed it, so the client
 * fell back to `./pubky-swap-client-data` relative to the server's working directory -- inside the
 * container image rather than on the persistent volume. A submarine swap's refund key is generated
 * there and exists nowhere else; losing it makes the on-chain output unspendable by anyone.
 */
function clientConfig(cfg, { dataDir, provider, direction, amount }) {
  return {
    ...backends(),
    data_dir: dataDir,
    provider_pkarr: provider || undefined,
    direction: direction || undefined,
    amount_sat: amount || undefined,
    onchain_fee_rate_sat_vb: cfg.onchainFeeRate,
    max_routing_fee_msat: cfg.maxRoutingFeeMsat,
    // The operator's own guards, not the provider's.
    min_confirmations: cfg.takerMinConfirmations,
    max_fee_bps: cfg.takerMaxFeeBps,
    max_total_sat: cfg.takerMaxTotalSat || undefined,
    claim_address: cfg.takerClaimAddress || undefined,
    recovery_file: secrets.recoveryFilePath() || undefined,
  };
}

function writeConfig(file, config) {
  writeAtomic(file, toml.emit(config, HEADER), 0o600);
  return file;
}

/**
 * The child environment: a whitelist of the handful of variables a daemon legitimately needs,
 * plus the identity paths. Nothing is inherited from this process's own PUBKY_SWAP_* namespace.
 */
function childEnv(configPath, extra = {}) {
  const env = {
    PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin',
    HOME: process.env.HOME || '/tmp',
    LANG: process.env.LANG || 'C.UTF-8',
    RUST_LOG: process.env.RUST_LOG || 'info',
    PUBKY_SWAP_CONFIG: configPath,
    ...secrets.identityEnv(),
    ...extra,
  };
  return env;
}

module.exports = {
  NETWORK, LND_IP, LND_GRPC_PORT, LND_DIR, ELECTRS_IP, ELECTRS_PORT, LND_NETWORK_DIR,
  backends, providerConfig, clientConfig, writeConfig, childEnv,
};
