'use strict';

// Turning this app's settings into something the pubky-swap binaries will accept.
//
// Two rules run through everything here:
//
//   Nothing configurable goes on argv. Upstream resolves $PUBKY_SWAP_CONFIG ahead of the
//   environment and the flags, so a generated TOML is both the most direct way to configure the
//   daemon and the only way to guarantee that `--doctor` and `--show-config` report on exactly the
//   configuration the daemon will run with.
//
//   The child environment is built from a whitelist, never inherited wholesale. Any stray
//   PUBKY_SWAP_* variable in the container would be merged by figment at a layer *above* our file
//   and silently outrank it, so a typo in docker-compose.yml could quietly change a fee.

const path = require('path');
const paths = require('./paths');
const secrets = require('./secrets');
const toml = require('./toml');
const { writeAtomic } = require('./atomic');

const NETWORK = process.env.NETWORK || 'mainnet';
const LND_IP = process.env.LND_IP || '';
const LND_GRPC_PORT = process.env.LND_GRPC_PORT || '10009';
const LND_DIR = process.env.LND_DIR || '/lnd';
const ELECTRS_IP = process.env.ELECTRS_IP || '';
const ELECTRS_PORT = process.env.ELECTRS_PORT || '';

// Umbrel exports the chain as `mainnet`; the swap daemon calls the same chain `bitcoin`. Getting
// this wrong is not a cosmetic mismatch: it decides which chain addresses are derived on.
const SWAP_NETWORK =
  { mainnet: 'bitcoin', bitcoin: 'bitcoin', testnet: 'testnet', signet: 'signet', regtest: 'regtest' }[NETWORK] || 'bitcoin';

// LND keeps its chain data under data/chain/bitcoin/<mainnet|testnet|signet|regtest>/.
const LND_NETWORK_DIR =
  { bitcoin: 'mainnet', mainnet: 'mainnet', testnet: 'testnet', signet: 'signet', regtest: 'regtest' }[NETWORK] || 'mainnet';

/**
 * One-click Electrum servers.
 *
 * Umbrel's Electrs, Fulcrum and ElectrumX apps sit at fixed addresses on the shared app network,
 * published in each one's `exports.sh`, and are reachable from here whether or not this app
 * declares a dependency on any of them. It deliberately declares none: declaring one would make
 * umbrelOS insist on that specific app, so an operator already running Fulcrum would be told to
 * install Electrs to use a swap provider that does not need it.
 *
 * The ports differ, which is the detail that makes any hardcoded default wrong for somebody:
 * Electrs and ElectrumX listen on 50001, Fulcrum on 50002.
 */
const ELECTRUM_PRESETS = [
  { id: 'electrs', label: 'Umbrel Electrs', host: '10.21.21.10', port: 50001 },
  { id: 'fulcrum', label: 'Umbrel Fulcrum', host: '10.21.21.200', port: 50002 },
  { id: 'electrumx', label: 'Umbrel ElectrumX', host: '10.21.21.199', port: 50001 },
];

/**
 * The Electrum URL both binaries are given.
 *
 * One place, so a provider and a taker swap on the same node can never disagree about which
 * server they are asking.
 */
function electrumUrl(cfg) {
  const host = String(cfg.electrumHost || '').trim();
  const port = Number(cfg.electrumPort) || ELECTRUM_PRESETS[0].port;
  return `tcp://${host}:${port}`;
}

const HEADER =
  'Generated by the Pubky Swap Umbrel app. Edits here are overwritten every time the daemon\n' +
  'starts; change the settings in the web panel instead.\n' +
  'Secrets are deliberately absent: they are passed as PUBKY_SWAP_*__FILE paths.';

/** The backend settings both binaries share. */
function backends(cfg) {
  return {
    network: SWAP_NETWORK,
    lightning_backend: 'lnd',
    lnd_address: `https://${LND_IP}:${LND_GRPC_PORT}`,
    lnd_cert_path: path.join(LND_DIR, 'tls.cert'),
    lnd_macaroon_path: path.join(LND_DIR, 'data', 'chain', 'bitcoin', LND_NETWORK_DIR, 'admin.macaroon'),
    electrum_url: electrumUrl(cfg),
    // Fund and claim from LND's own on-chain wallet, so there is no second seed to back up.
    wallet_backend: 'lnd',
  };
}

/**
 * The provider's configuration.
 *
 * Deliberately absent: `min_claim_window_blocks`, `peer_idle_ttl_secs` and
 * `electrum_timeout_secs`. Those are safety and behaviour constants the engine tunes for itself,
 * and pinning them here would mean an upstream safety improvement never reaches anyone.
 */
function providerConfig(cfg, statusAddr) {
  return {
    ...backends(cfg),
    directions: cfg.directions.split(','),
    min_amount_sat: cfg.minAmount,
    max_amount_sat: cfg.maxAmount,
    base_fee_sat: cfg.baseFee,
    fee_ppm: cfg.feePpm,
    required_confirmations: cfg.confirmations,
    htlc_timeout_blocks: cfg.timeoutBlocks,
    onchain_fee_rate_sat_vb: cfg.onchainFeeRate,
    invoice_expiry_secs: cfg.invoiceExpiry,
    max_routing_fee_msat: cfg.maxRoutingFeeMsat,
    quote_ttl_secs: cfg.quoteTtl,
    broadcast_offer: cfg.broadcastOffer,
    allow_unsafe: cfg.allowUnsafe,

    max_concurrent_swaps: cfg.maxConcurrentSwaps,
    max_concurrent_per_peer: cfg.maxConcurrentPerPeer,
    max_total_exposure_sat: cfg.maxTotalExposureSat,
    max_exposure_per_peer_sat: cfg.maxExposurePerPeerSat,
    min_onchain_reserve_sat: cfg.minOnchainReserveSat,
    max_new_swaps_per_peer_per_hour: cfg.maxNewSwapsPerPeerPerHour,

    data_dir: paths.providerDir,
    status_addr: statusAddr,
    // Answer the doorbell, so someone handed only your pubky can reach you.
    //
    // Pubky's private messages live at a path derived from an ECDH shared secret, which is what
    // makes them unlinkable and also means there is no "who has written to me": a provider can
    // only fetch messages from pubkys it already knows, which is its follow graph. Without the
    // rendezvous, "share your pubky with anyone who wants to swap" is not a thing that works.
    // Written explicitly rather than left to the default, because it is load-bearing.
    rendezvous_iroh: true,
    recovery_file: secrets.recoveryFilePath() || undefined,
  };
}

/**
 * The taker's configuration for one run.
 *
 * `data_dir` is the whole point of this function. An earlier build never passed it, so the client
 * fell back to `./pubky-swap-client-data` relative to the server's working directory -- inside the
 * container image rather than on the persistent volume. A submarine swap's refund key is generated
 * there and exists nowhere else; losing it makes the on-chain output unspendable by anyone.
 */
function clientConfig(cfg, { dataDir, provider, direction, amount }) {
  return {
    ...backends(cfg),
    data_dir: dataDir,
    provider_pkarr: provider || undefined,
    direction: direction || undefined,
    amount_sat: amount || undefined,
    onchain_fee_rate_sat_vb: cfg.onchainFeeRate,
    max_routing_fee_msat: cfg.maxRoutingFeeMsat,
    // The operator's own guards, not the provider's.
    min_confirmations: cfg.takerMinConfirmations,
    max_fee_bps: cfg.takerMaxFeeBps,
    max_total_sat: cfg.takerMaxTotalSat || undefined,
    claim_address: cfg.takerClaimAddress || undefined,
    recovery_file: secrets.recoveryFilePath() || undefined,
  };
}

function writeConfig(file, config) {
  writeAtomic(file, toml.emit(config, HEADER), 0o600);
  return file;
}

/**
 * The child environment: a whitelist of the handful of variables a daemon legitimately needs,
 * plus the identity paths. Nothing is inherited from this process's own PUBKY_SWAP_* namespace.
 */
function childEnv(configPath, extra = {}) {
  const env = {
    PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin',
    HOME: process.env.HOME || '/tmp',
    LANG: process.env.LANG || 'C.UTF-8',
    RUST_LOG: process.env.RUST_LOG || 'info',
    // This log is read in a browser, not a terminal. tracing colourises whenever it is not
    // writing to a tty, so without this every line arrives wrapped in escape sequences.
    NO_COLOR: '1',
    // Deliberately no PUBKY_SWAP_DATA_DIR. The environment layer sits *above* the config file in
    // the engine's precedence, so that variable does not merely locate the config, it overrides
    // the `data_dir` inside it. Setting it to the provider's directory sent the taker's swap
    // records there: not lost, but the panel could not find them, so a swap that had completely
    // succeeded reported an unknown outcome, and the provider counted a taker's swaps among its
    // own earnings. `PUBKY_SWAP_CONFIG` names the file directly, so nothing needs the data
    // directory to find it.
    PUBKY_SWAP_CONFIG: configPath,
    ...secrets.identityEnv(),
    ...extra,
  };
  return env;
}

module.exports = {
  NETWORK, SWAP_NETWORK, LND_IP, LND_GRPC_PORT, LND_DIR, ELECTRS_IP, ELECTRS_PORT,
  LND_NETWORK_DIR, ELECTRUM_PRESETS, electrumUrl,
  backends, providerConfig, clientConfig, writeConfig, childEnv,
};
